apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-pulse-ingestor.fullname" . }}
  labels:
    {{- include "log-pulse-ingestor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "log-pulse-ingestor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "log-pulse-ingestor.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "log-pulse-ingestor.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.appConfig.grpc.port }}
#            - name: http
#              containerPort: {{ .Values.service.port }}
#              protocol: TCP
          volumeMounts:
            - name: config-template
              mountPath: /etc/config
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
          env:
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "log-pulse-ingestor.fullname" . }}-passwords
                  key: clickhouse-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "log-pulse-ingestor.fullname" . }}-passwords
                  key: redis-password
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              envsubst < /etc/config/app.conf.yml > /app/app.conf.yml;
              cd /app && ./log-pulse-ingestor
      volumes:
        - name: config-template
          configMap:
            name: {{ include "log-pulse-ingestor.fullname" . }}-config
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}