apiVersion: v1
kind: Secret
metadata:
    name: {{ include "log-pulse-ingestor.fullname" . }}-passwords
type: Opaque
stringData:
    clickhouse-password: {{ .Values.secrets.clickhousePassword | quote }}
    redis-password: {{ .Values.secrets.redisPassword | quote }}
