apiVersion: v1
kind: Service
metadata:
  name: {{ include "log-pulse-ingestor.fullname" . }}
  labels:
    {{- include "log-pulse-ingestor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.appConfig.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "log-pulse-ingestor.selectorLabels" . | nindent 4 }}
