version: 2

updates:
    - package-ecosystem: "cargo"
      directory: "/app"
      schedule:
          interval: "monthly"
      assignees:
          - "John361"
      prefix: "deps-cargo"

    - package-ecosystem: "docker"
      directory: "/app"
      schedule:
          interval: "monthly"
      assignees:
          - "John361"
      prefix: "deps-docker"

    - package-ecosystem: "docker-compose"
      directory: "/docker"
      schedule:
          interval: "monthly"
      assignees:
          - "John361"
      prefix: "deps-docker-compose"

    - package-ecosystem: "helm"
      directory: "/charts"
      schedule:
          interval: "monthly"
      assignees:
          - "John361"
      prefix: "deps-helm"
